quality/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('products.urls', namespace='products')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quality/products/urls.py
# -*- coding: utf-8 -*-
"""Products app urls."""
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'^products/add/$',
        views.ProductAdd.as_view(),
        name='add'
    ),
    url(
        r'^products/(?P<slug>[\w-]+)/$',
        views.ProductEdit.as_view(),
        name='edit'
    ),
    url(
        r'^products/(?P<slug>[\w-]+)/delete/$',
        views.ProductDelete.as_view(),
        name='delete'
    ),
    url(
        r'^$',
        views.ProductList.as_view(),
        name='list'
    ),
]

quality/products/models.py
# -*- coding: utf-8 -*-
"""Products app models."""
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models


class Size(models.Model):
    name = models.CharField(max_length=8, verbose_name='nome')
    slug = models.SlugField(verbose_name='slug')

    def __unicode__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=16, verbose_name='nome')
    slug = models.SlugField(verbose_name='slug')
    description = models.TextField(blank=True, verbose_name='descrição')
    sizes = models.ManyToManyField(Size, verbose_name='tamanhos')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('produts:list')

quality/products/forms.py
# -*- coding: utf-8 -*-
"""Products app forms."""
from django import forms
from django.utils.text import slugify

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name',
            'description',
            'sizes',
        )

    def save(self, commit=True, *args, **kwargs):
        instance = super(ProductForm, self).save(commit=False, *args, **kwargs)
        name = self.cleaned_data['name']
        instance.slug = slugify(name)
        if commit:
            instance.save()
        return instance

quality/products/views.py
# -*- coding: utf-8 -*-
"""Products app views."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views import generic

from .forms import ProductForm
from .models import Product


class ProductMixin(object):
    model = Product


class ProductList(ProductMixin, generic.ListView):
    template_name = 'products/list.html'
    context_object_name = 'products'


class ProductAdd(LoginRequiredMixin, ProductMixin, generic.CreateView):
    template_name = 'products/form.html'
    success_url = reverse_lazy('products:list')
    form_class = ProductForm


class ProductEdit(ProductMixin, generic.UpdateView):
    template_name = 'products/form.html'
    success_url = reverse_lazy('products:list')
    form_class = ProductForm


class ProductDelete(LoginRequiredMixin, ProductMixin, generic.DeleteView):
    template_name = 'delete.html'
    success_url = reverse_lazy('products:list')

quality/templates/base.html
<!DOCTYPE html>
<html>
<head lang="pt">
	<meta charset="utf8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>QA</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Mudar navegação</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">QA</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				{% if not request.user.is_authenticated %}
					<form id="login" class="navbar-form navbar-right" action="{% url 'login' %}" method="POST">
						{% csrf_token %}
            {% if redirect_field_value %}
              <input type="hidden" name="{{ redirect_field_value }}" value="{{ redirect_field_value }}">
            {% endif %}
						<div class="form-group">
							<input class="form-control" type="text" name="username" placeholder="Username">
						</div>
						<div class="form-group">
							<input class="form-control" type="password" name="password" placeholder="Password">
						</div>
						<button type="submit" class="btn btn-default">Entrar</button>
					</form>
				{% else %}
					<form id="logout" class="navbar-form navbar-right" action="{% url 'logout' %}" method="POST">
						{% csrf_token %}
            {% if redirect_field_value %}
              <input type="hidden" name="{{ redirect_field_value }}" value="{{ redirect_field_value }}">
            {% endif %}
						<button type="submit" class="btn btn-default">Sair</button>
					</form>
				{% endif %}
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
	<div id="container-fluid">
		{% block content %}
		{% endblock content %}
	</div>
	<script src="http://code.jquery.com/jquery-2.2.1.min.js">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

quality/templates/delete.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-sm-11 col-sm-offset-1">
      <p>De certeza que quer apagar <strong>{{ product }}</strong>?</p>
      <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
          <div class="col-sm-offset-1 col-sm-11">
            <button type="submit" class="btn btn-danger">Apagar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

quality/templates/partials/form.html
{% csrf_token %}
{% for hidden in form.hidden_fields %}
  {{ hidden }}
{% endfor %}
{{ form.non_field_errors }}
{% for field in form.visible_fields %}
  <div class="form-group">
    {% if field.errors %}<p>{{ field.errors }}</p>{% endif %}
    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
    <div class="col-sm-10">
      {{ field }}
    </div>
  </div>
{% endfor %}

quality/templates/products/form.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
        {% include "partials/form.html" %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Guardar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

quality/templates/products/list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-12">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Produto</th>
          <th>Tamanhos</th>
          {% if request.user.is_authenticated %}
            <th>Acções</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
			  {% for prod in products %}
          <tr>
            <td>{{ prod }}</td>
            <td>{% for size in prod.sizes.all %}{% if forloop.last %}{{ size }}{% else %}{{ size }}, {% endif %}{% endfor %}</td>
            {% if request.user.is_authenticated %}
              <td>
                <a href="{% url 'products:edit' prod.slug %}" class="btn btn-default btn-xs">Editar</a>
                <a href="{% url 'products:delete' prod.slug %}" class="btn btn-danger btn-xs">Apagar</a>
              </td>
            {% endif %}
          </tr>
			  {% endfor %}
      </tbody>
    </table>
    {% if request.user.is_authenticated %}
      <div class="row">
        <div class="col-md-3 col-md-offset-9">
          <a href="{% url 'products:add' %}" class="btn btn-default btn-mini" role="button">Novo produto</a>
        </div>
      </div>
    {% endif %}
	</div>
</div>
{% endblock content %}